### PR TITLE
Website Redesign Pt.1

### PR DESCRIPTION
**Pull request by MoonTM-GIT**
I'm currently working on redesigning the Website according to [this](https://www.figma.com/proto/PWu5nh7kjJxD8v1uVG0wJB/javadiscord-web?node-id=3%3A5&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A5&hide-ui=1) design proposal.

### CODE REVIEW

**Comment by MoonTM-GIT** [comment]
For anyone interested, this is what the "home" page looks like, everything is responsive although that might require a few finishing touches to make it look a bit better


https://user-images.githubusercontent.com/66334318/164454338-31ed024b-473d-418c-b305-50ac9210a9df.mp4

**Comment by MoonTM-GIT** [comment]
Oh, and "other" in the navbar is going to become a dropdown as can be seen on that figma page

**Comment by MoonTM-GIT** [comment]
404 Page:
image

**Comment by MoonTM-GIT** [comment]
test

**Comment by jasonlessenich** [comment]
Oops

**Comment by MoonTM-GIT** [comment]
😡

**Comment by MoonTM-GIT** [comment]
We have decided to against the rules page on Figma, it just doesn't look good with the length of the rules we have now. Instead I've made this:

https://user-images.githubusercontent.com/66334318/165138515-d3bd6245-03f3-403d-8fb2-d1fcfb30984b.mp4

**Comment by MoonTM-GIT** [comment]
TODO:

- [ ] Profile Page
- [ ] Other

**Pull request merged**
